image:
  file: /.gitpod/Dockerfile

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    addCheck: false
    addComment: false

tasks:
  - name: Initialize Bazel
    init: >
      bazelisk --version &&
      ln -sf /workspace/go/bin/bazelisk /workspace/go/bin/bazel &&
      bazel --version &&
      exit &&
      gp sync-done INITIALIZE_BAZEL

  - name: Initialize Trunk
    init: >
      trunk install &&
      trunk upgrade &&
      exit

  - name: Build Gazelle
    init: >
      gp sync-await INITIALIZE_BAZEL &&
      bazelisk build //:gazelle &&
      exit
